site_name: SepicServer Docs
site_url: http://firesepichub-14.github.io/
strict: false
copyright: Copyright &copy; 2021 - 2026 sou@SepicServer

theme:
  name: material

  logo: img/logo.png
  favicon: img/favicon.png

  font:
    text: Kosugi
    code: Inconsolata

  palette:
  - scheme: default
    primary: pink
    accent: yellow
    toggle:
      icon: material/lightbulb
      name: Switch to light mode

  - scheme: slate
    primary: teal
    accent: deep orange
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

  features:
  - search.highlight
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.footer
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - navigation.path
  - content.code.copy
  - content.footnote.tooltips
  - toc.integrate

plugins:
- search:
    separator: '[\s\-\.]+'
    prebuild_index: true
- encryptcontent: {}
- tags:
    tags_allowed:
    - Address
    - Minecraft
    - Mods
    - Rule
    - SepicServer
    - Streaming
    tags_extra_files:
      compatibility.md:
      - compatibility
      changelog.md:
      - changelog

- table-reader # CSVãƒ•ã‚¡ã‚¤ãƒ«ã‹ã‚‰ãƒ†ãƒ¼ãƒ–ãƒ«ã‚’ç”Ÿæˆ

extra:
  # copyright
  generator: false

  # ã‚½ãƒ¼ã‚·ãƒ£ãƒ«ãƒªãƒ³ã‚¯
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/FireSepicHub-14
  - icon: fontawesome/brands/discord
    link: https://discord.gg/UK6meefHar
    name: SepicServer Discord

extra_css:
- stylesheets/extra.css

markdown_extensions:
- admonition # æ³¨æ„æ›¸ã
- pymdownx.details # æŠ˜ã‚ŠãŸãŸã¿
- pymdownx.superfences # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯æ”¹å–„
- pymdownx.critic
- pymdownx.caret
- attr_list # å±æ€§ãƒªã‚¹ãƒˆ
- pymdownx.tabbed:
    # ã‚¿ãƒ–è¡¨ç¤º
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.mark # ãƒãƒ¼ã‚«ãƒ¼
- pymdownx.keys # ã‚­ãƒ¼ãƒœãƒ¼ãƒ‰ã‚­ãƒ¼
- pymdownx.tilde # å–ã‚Šæ¶ˆã—ç·š
- md_in_html # HTMLå†…Markdown
- footnotes

# ãƒ«ãƒ¼ãƒˆï¼ˆè¨€èªé¸æŠãƒšãƒ¼ã‚¸ + ãƒ†ã‚¹ãƒˆï¼‰
nav:
# - Language:
#   - æ—¥æœ¬èª / Japanese: ja/
#   - English: en/
- Home: index.md
- ãƒ«ãƒ¼ãƒ«ãƒ–ãƒƒã‚¯ğŸ“š:
  - â”â” ã“ã®ã‚«ãƒ†ã‚´ãƒªãƒ¼ã¯ï¼Ÿ â”â”: ja/rule/index.md
  - â”â” åˆ©ç”¨è¦ç´„ â”â”: ja/rule/SepicServerGroup_ToU.md
  - â”â” SNSé…ä¿¡ã«ã¤ã„ã¦ â”â”: ja/rule/sns_streaming.md
  - â”â” å®£ä¼è¡Œç‚ºã«ã¤ã„ã¦ â”â”: ja/rule/AdvertisingPolicy.md
  - â”â” ä½¿ç”¨å¯èƒ½McMods â”â”: ja/rule/Approved-mods.md
- Sepic Minecrafté¯–:
  - â”â” ã“ã®ã‚«ãƒ†ã‚´ãƒªãƒ¼ã¯ï¼Ÿ â”â”: ja/mc_svr/index.md
  - â”â” ã‚µãƒ¼ãƒãƒ¼ã‚¢ãƒ‰ãƒ¬ã‚¹ â”â”: ja/mc_svr/ServerAddress.md
  - â”â” æ¨å¥¨æ§‹æˆ â”â”: ja/mc_svr/RecommendedConfiguration.md
- AdminPage:
  - â”â” ã“ã®ã‚«ãƒ†ã‚´ãƒªãƒ¼ã¯ï¼Ÿ â”â”: ja/pass_test/index.md